apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongo
    type: db
spec:
  type: NodePort
  ports:
    - targetPort: 27017
      port: 27017
      nodePort: 30007
  selector:
      type: db