apiVersion: v1
kind: Service
metadata:
  name: hygieia-ui-service
  labels:
    app: hygieia-ui
    type: hygieia-ui
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 3000
      nodePort: 30005
  selector:
      type: frontend