apiVersion: v1
kind: Service
metadata:
  name: hygieia-api-service
  labels:
    app: hygieia-api
    type: backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
      app: hygieia-api 